configs: rk33xx: only enable new display for rk3399
fix complie error:
    undefined reference to `rkclk_lcdc_dclk_pll_sel'

only rk3399 support rkclk_lcdc_dclk_pll_sel function, now
it's required by new display vop.

Change-Id: I850f29a6fd50600479c94f8f19d464daaeb9cce6
Signed-off-by: Mark Yao <mark.yao@rock-chips.com>